### ISSUE TITLE
SoapFault exception: [s:Sender] An error occurred when verifying security for the message

### ISSUE THREAD

**Issue by andela-doladosu** [AlexaCRM/php-crm-toolkit#29]
Hi,
When trying to connect to the crm api, I'm getting the error
```
SoapFault exception: [s:Sender] An error occurred when verifying security for the message. in /var/www/local-api.cskout.com/vendor/alexacrm/php-crm-toolkit/src/Client.php:1311
Stack trace:
#0 /var/www/local-api.cskout.com/vendor/alexacrm/php-crm-toolkit/src/Client.php(1056): AlexaCRM\CRMToolkit\Client::getSoapResponse('https://disco.c...', '<s:Envelope xml...')
#1 /var/www/local-api.cskout.com/vendor/alexacrm/php-crm-toolkit/src/Client.php(1104): AlexaCRM\CRMToolkit\Client->retrieveOrganizations()
#2 /var/www/local-api.cskout.com/vendor/alexacrm/php-crm-toolkit/src/Client.php(183): AlexaCRM\CRMToolkit\Client->retrieveOrganization('https://growthe...')
#3 /var/www/local-api.cskout.com/library/Connectors/Connectors/MicrosoftDynamicsConnector.php(74): AlexaCRM\CRMToolkit\Client->__construct(Object(AlexaCRM\CRMToolkit\Settings))
#4 /var/www/local-api.cskout.com/library/Connectors/Connectors/MicrosoftDynamicsConnector.php(152): Crowdskout\Api\Connectors\Connectors\MicrosoftDynamicsConnector->authenticate()```

Could you offer any pointers on what I could be doing wrong that is causing this error?

**Comment by georged** [comment]
Hi @andela-doladosu 

double-check that the time on your server is correct. If clock is off by I think more than 2 minutes, you will get this error.

Thanks
George

**Comment by andela-doladosu** [comment]
Thanks! @georged 

Sorry, I'm not at all familiar with crm. Could you give me any pointers on how to adjust the time on my server?

**Comment by georged** [comment]
@andela-doladosu I'm talking about the system clock on the server hosting your website, not crm one.

**Comment by andela-doladosu** [comment]
Our servers are hosted locally in vagrant. A co-worker ran `sudo ntpdate pool.ntp.org` on his vagrant box, and that got rid of the error. I'm going to do some more testing on my end to see if it definitely fixes the issue for me too.

Thanks @georged!
